default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: query_string_to_sql_development
  
production:
  <<: *default
  database: query_string_to_sql_production
  username: query_string_to_sql
  password: <%= ENV['QUERY_STRING_TO_SQL_DATABASE_PASSWORD'] %>
